services:
  localstack:
    container_name: aws_localstack
    image: localstack/localstack:1.2.0
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DISABLE_CORS_CHECKS=1
